export const LOAD_DICTIONARY = 'LOAD_DICTIONARY'
export const LOAD_CAPTCHA = 'LOAD_CAPTCHA'

export const REGISTER_USER = 'REGISTER_USER'
export const ACTIVATE_USER = 'ACTIVATE_USER'
export const AUTHORIZE_USER = 'AUTHORIZE_USER'
export const LOGOUT_USER = 'LOGOUT_USER'

export const RESET_PASSWORD = 'RESET_PASSWORD'
export const SET_PASSWORD = 'SET_PASSWORD'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'

export const LOAD_PROFILE = 'LOAD_PROFILE'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'

export const SUCCESS = '_SUCCESS'
export const START = '_START'
export const FAIL = '_FAIL'
