export const LOAD_DICTIONARY = 'LOAD_DICTIONARY'
export const LOAD_CAPTCHA = 'LOAD_CAPTCHA'

export const REGISTER_USER = 'REGISTER_USER'
export const SIGN_UP_STATUS_CLEAN = 'SIGN_UP_STATUS_CLEAN'

export const ACTIVATE_USER = 'ACTIVATE_USER'
export const AUTHORIZE_USER = 'AUTHORIZE_USER'
export const SIGN_IN_STATUS_CLEAN = 'SIGN_IN_STATUS_CLEAN'
export const LOGOUT_USER = 'LOGOUT_USER'

export const RESET_PASSWORD = 'RESET_PASSWORD'
export const FORGOT_STATUS_CLEAN = 'FORGOT_CLEAN'
export const SET_PASSWORD = 'SET_PASSWORD'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'

export const CHANGE_EMAIL = 'CHANGE_EMAIL'
export const CONFIRM_EMAIL = 'CONFIRM_EMAIL'
export const EMAIL_STATUS_CLEAN = 'EMAIL_STATUS_CLEAN'

export const UPLOAD_SNILS = 'UPLOAD_SNILS'
export const DOWNLOAD_SNILS = 'DOWNLOAD_SNILS'
export const SNILS_STATUS_CLEAN = 'SNILS_STATUS_CLEAN'

export const LOAD_PROFILE = 'LOAD_PROFILE'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const PERSONAL_DATA_STATUS_CLEAN = 'PERSONAL_DATA_STATUS_CLEAN'

export const SUCCESS = '_SUCCESS'
export const START = '_START'
export const FAIL = '_FAIL'